<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\countries;
use App\Models\states;
use App\Models\cities;
use DB;

class IntegrationController extends Controller
{
    public function getcountry()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt(
            $ch,
            CURLOPT_URL,
            "https://api.countrystatecity.in/v1/countries"
        );
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

        $headers = [];
        $headers[] = "Accept: application/json";
        $headers[] =
            "X-Cscapi-Key: MUQzMEptNEE3bXZTNVhSQUVtNEVBNk9ZakgzRk9wcUdFYnJjT0EwNQ==";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo "Error:" . curl_error($ch);
        }
        curl_close($ch);

        $result = json_decode($result);

        $i = 0;

        foreach ($result as $countrylist) {
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $url =
                "https://api.countrystatecity.in/v1/countries/" .
                $countrylist->iso2;
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
            $headers = [];
            $headers[] = "Accept: application/json";
            $headers[] =
                "X-Cscapi-Key: MUQzMEptNEE3bXZTNVhSQUVtNEVBNk9ZakgzRk9wcUdFYnJjT0EwNQ==";
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo "Error:" . curl_error($ch);
            }
            curl_close($ch);
            $result = json_decode($result);
            $countries = countries::create([
                "name" => $result->name,
                "iso3" => $result->iso3,
                "iso2" => $result->iso2,
                "phonecode" => $result->phonecode,
                "capital" => $result->capital,
                "currency" => $result->currency,
                "native" => $result->native,
                "emoji" => $result->emoji,
                "emojiU" => $result->emojiU,
            ]);
            if ($i == 100) {
                break;
            }
            $i++;
        }
        return "Success";
    }
    public function getstates()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt(
            $ch,
            CURLOPT_URL,
            "https://api.countrystatecity.in/v1/states"
        );
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

        $headers = [];
        $headers[] = "Accept: application/json";
        $headers[] =
            "X-Cscapi-Key: MUQzMEptNEE3bXZTNVhSQUVtNEVBNk9ZakgzRk9wcUdFYnJjT0EwNQ==";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo "Error:" . curl_error($ch);
        }
        curl_close($ch);
        $result = json_decode($result);

        foreach ($result as $data) {
            $states = states::create([
                "name" => $data->name,
                "country_id" => $data->country_id,
                "country_code" => $data->country_code,
                "iso2" => $data->iso2,
            ]);
        }
        return "Success";
    }
    public function getcity()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt(
            $ch,
            CURLOPT_URL,
            "https://api.countrystatecity.in/v1/countries/IN/states/TN/cities"
        );
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

        $headers = [];
        $headers[] = "Accept: application/json";
        $headers[] =
            "X-Cscapi-Key: MUQzMEptNEE3bXZTNVhSQUVtNEVBNk9ZakgzRk9wcUdFYnJjT0EwNQ==";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo "Error:" . curl_error($ch);
        }
        curl_close($ch);
        $result = json_decode($result);

        foreach ($result as $data) {
            $states = cities::create([
                "name" => $data->name,
                "state_id" => $data->id,
                "state_code" => "TN",
                "country_id" => "4035",
                "country_code" => "IN",
                "latitude" => "11.12712250",
                "longitude" => "78.65689420",
            ]);
        }
        return "Success";
    }
}